vsync = true;
backend = "glx";
shadow = true;
shadow-radius = 24;
corner-radius = 24;
shadow-opacity = 0.5;
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
blur-background = true;
# blur-method = "kawase";
