[language-server.gpt]
command = "helix-gpt --handler copilot"
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [ "vscode-html-language-server", "tailwindcss-ls", "gpt", "emmet-lsp" ]
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls", "gpt" ]
[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [ "typescript-language-server", "tailwindcss-ls", "gpt", "emmet-lsp"]
auto-format = true
[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls", "gpt", "emmet-lsp" ]
[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "gpt", "emmet-lsp" ]
[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls", "gpt", "emmet-lsp" ]
