return {}
-- return {
--   -- Enable cmdline completion for :
--   {
--     "hrsh7th/cmp-cmdline",
--     dependencies = { "hrsh7th/nvim-cmp" },
--     config = function()
--       local cmp = require("cmp")
--
--       -- `:` command line completion
--       cmp.setup.cmdline(":", {
--         mapping = cmp.mapping.preset.cmdline(),
--         sources = cmp.config.sources({
--           { name = "cmdline" },
--         }),
--       })
--
--       -- `/` and `?` search completion (optional)
--       cmp.setup.cmdline({ "/", "?" }, {
--         mapping = cmp.mapping.preset.cmdline(),
--         sources = {
--           { name = "buffer" },
--         },
--       })
--     end,
--   },
-- }
